[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true

[project]
name = "codescribe-agent"
version = "0.1.0"
description = "AI-powered documentation generator for Python projects"
readme = "README.md"
requires-python = ">=3.10"
license = "AGPL-3.0-or-later"

authors = [
    {name = "Abhay Singh"}
]

dependencies = [
    "click",
    "pathspec>=1.0.3",
    "pyyaml",
    "rich",
    "python-dotenv",
    "groq>=1.1.1"
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "twine>=6.2.0"
]

[project.urls]
Homepage = "https://github.com/Justt-Abhayyy/CodeScribe"
Repository = "https://github.com/Justt-Abhayyy/CodeScribe"
Issues = "https://github.com/Justt-Abhayyy/CodeScribe/issues"

[project.scripts]
codescribe = "CodeScribe.pipelines.supervisor:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["CodeScribe*"]

[tool.setuptools.package-data]
"CodeScribe" = ["resources/*.gitignore"]